version: "3"
services:
  hub:
    image: selenium/hub:3.141
    ports:
      - "4444:4444"
      - "5900:5900"
  chrome:
    image: selenium/node-chrome-debug:3.141
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - "/dev/shm:/dev/shm"
  firefox:
    image: selenium/node-firefox-debug:3.141
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - "/dev/shm:/dev/shm"
